var PLANET_WIDTH = 2048;
var PLANET_HEIGHT = 128;
var PLANET_MAX_HEIGHT = 80;
var PLANET_PERSISTANCE = 0.5;
var PLANET_OCTAVES_NUMBER = 4;
var PLANET_STEP = 64;

var PLAYER_WIDTH = 32;
var PLAYER_HEIGHT = 32;
var PLAYER_SPEED_X = 3;
var PLAYER_START_X = 240;
var PLAYER_START_Y = 550;
var PLAYER_START_SPEED_Y = -0.01;
var PLAYER_Y_SPEED_INCRETION = 0.0001;
var PLAYER_MAX_LASERS = 5;
var PLAYER_LASER_RECOVERY = 40;

var LASER_WIDTH = 5;
var LASER_HEIGHT = 20;

var ENEMY_WIDTH = 32;
var ENEMY_HEIGHT = 32;

var CITY_POS_Y = 40;
var CITY_WIDTH = 20;
var CITY_HEIGHT = 20;
var CITY_MAX_LIFE = 5;

var PLANET_DEVIATION = 64;

var SPAWN_ENEMY_HEIGHT = PLANET_HEIGHT + 32;
var SPAWN_ENEMY_LAYERS_NUMBER = 5;
var SPAWN_ENEMY_LAYER_PERSISTANCE = 0.6;
var SPAWN_ENEMY_LAYER_HEIGHT = ENEMY_HEIGHT + 25;

var KEY_LEFT = 37;
var KEY_RIGHT = 39;
var KEY_SPACE = 32;