var PLAYER_WIDTH = 32;
var PLAYER_HEIGHT = 32;
var PLAYER_SPEED_X = 3;
var PLAYER_START_X = 240;
var PLAYER_START_Y = 550;
var PLAYER_START_SPEED_Y = -0.01;
var PLAYER_Y_SPEED_INCRETION = 0.0001;

var LASER_WIDTH = 5;
var LASER_HEIGHT = 20;

var ENEMY_WIDTH = 32;
var ENEMY_HEIGHT = 32;

var CITY_WIDTH = 20;
var CITY_HEIGHT = 20;

var PLANET_DEVIATION = 64;